# Auto-generated by Register-CleanupSuite.ps1
# Послідовний запуск: Cleanup v2 -> Health

\Stop = 'Stop'

Write-Host "[CleanupSuite] START: \2025-09-11 18:16:43"
try {
    Write-Host "[CleanupSuite] Run CLEANUP v2"
    & C:\\Program Files\\PowerShell\\7\\pwsh.exe -NoProfile -ExecutionPolicy Bypass -File "D:\\CHECHA_CORE\C11\\tools\Cleanup-C11-Tools_v2.ps1" -Root "D:\\CHECHA_CORE" @(
    
    ) @(
    
    )
}
catch {
    Write-Host "[CleanupSuite] CLEANUP ERROR: \" -ForegroundColor Red
}

try {
    Write-Host "[CleanupSuite] Run HEALTH"
    & C:\\Program Files\\PowerShell\\7\\pwsh.exe -NoProfile -ExecutionPolicy Bypass -File "D:\\CHECHA_CORE\C11\\tools\Check-C11-ToolsHealth.ps1" -Root "D:\\CHECHA_CORE"
}
catch {
    Write-Host "[CleanupSuite] HEALTH ERROR: \" -ForegroundColor Red
}

Write-Host "[CleanupSuite] DONE: \2025-09-11 18:16:43"


