<#
.SYNOPSIS
  Run-EthicsSync.ps1 — аудит етичного блоку C02_ETHICS і створення звіту.
.DESCRIPTION
  Скрипт перевіряє цілісність файлів C02_ETHICS, наявність ключів data_sovereignty у C06_FOCUS,
  оновлення changelog і формує звіт ETHICS_SYNC у C03_LOG\reports.
#>

param(
    [string]$CoreRoot = "D:\CHECHA_CORE",
    [switch]$Pdf,
    [switch]$Silent
)

$ErrorActionPreference = "Stop"
$ts = Get-Date -Format "yyyy-MM-dd_HHmmss"
$day = Get-Date -Format "yyyy-MM-dd"
$ethics = Join-Path $CoreRoot "C02_ETHICS"
$focus  = Join-Path $CoreRoot "C06_FOCUS"
$logDir = Join-Path $CoreRoot "C03_LOG\reports"
$template = Join-Path $CoreRoot "C03_LOG\templates\ETHICS_SYNC_TEMPLATE.md"

# --- ensure dirs ---
if (!(Test-Path $logDir)) { New-Item -ItemType Directory -Force -Path $logDir | Out-Null }

function W($m, $lvl="INFO") {
    $c = if($lvl -eq "ERROR"){"Red"} elseif($lvl -eq "WARN"){"Yellow"} else {"Gray"}
    Write-Host "[$lvl] $m" -ForegroundColor $c
}

# --- collect status ---
$reportLines = @()
$ok = $true

function Add-Check($item, $okStatus, $note) {
    $emoji = if($okStatus){"✅"} else {"⚠️"}
    $reportLines += "| $item | $emoji | $note |"
    if(-not $okStatus){ Set-Variable -Name ok -Value $false -Scope 1 }
}

W "Scanning C02_ETHICS..."
$ethicsFiles = "C02_ETHICS.md","C02-INDEX.md","C02-CHANGELOG.md","C02.1_EthicalMatrix.md","C02.2_LawOfHarmony.md","C02.3_LawOfIntegrity.md","C02.4_DataSovereignty.md"
foreach($f in $ethicsFiles){
    $path = Join-Path $ethics $f
    Add-Check $f (Test-Path $path) ("Checked at $(Get-Date -Format 'HH:mm:ss')")
}

# --- check data_sovereignty tags ---
$focusFiles = Get-ChildItem $focus -Recurse -Filter *.md
$missing = @()
foreach($f in $focusFiles){
    $txt = Get-Content $f.FullName -Raw
    if($txt -notmatch "data_sovereignty: true"){ $missing += $f.Name }
}
if($missing.Count -eq 0){
    Add-Check "C06_FOCUS tags" $true "All files contain data_sovereignty:true"
} else {
    Add-Check "C06_FOCUS tags" $false ("Missing in: " + ($missing -join ', '))
}

# --- report template ---
if(!(Test-Path $template)){
    W "Template not found, using inline version" "WARN"
    $templateContent = @"
# ETHICS SYNC REPORT (autogenerated)
Date: $day
"@
} else {
    $templateContent = (Get-Content $template -Raw) -replace "{{date}}", $day
}

# --- insert table ---
$table = ($reportLines -join "`r`n")
$body = @"
$templateContent

## 🔍 Перевірено
$table

---

**Підпис:**  
С.Ч. | CHECHA_CORE | ETHICS_SYNC  
🜂 $day
"@

$outMd = Join-Path $logDir "ETHICS_SYNC_$day.md"
$outPdf = [System.IO.Path]::ChangeExtension($outMd, ".pdf")
$outSha = "$outPdf.sha256.txt"

$body | Out-File -Encoding UTF8 $outMd
W "Markdown report created: $outMd" "OK"

# --- optional PDF ---
if($Pdf){
    try {
        $css = Join-Path $CoreRoot "TOOLS\styles\checha_dark.css"
        pandoc $outMd -o $outPdf --pdf-engine=wkhtmltopdf --css $css --metadata title="ETHICS SYNC REPORT" --standalone
        if(Test-Path $outPdf){
            $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $outPdf).Hash
            "$hash  $(Split-Path $outPdf -Leaf)" | Out-File -Encoding ASCII $outSha
            W "PDF + SHA256 created: $outPdf" "OK"
        }
    } catch {
        W "PDF generation failed: $($_.Exception.Message)" "ERROR"
    }
}

if(-not $Silent){
    Write-Host "`n=== ETHICS SYNC SUMMARY ===" -ForegroundColor Cyan
    $reportLines | ForEach-Object { Write-Host $_ }
    if($ok){ Write-Host "`n✅ Ethics sync OK" -ForegroundColor Green } else { Write-Host "`n⚠️ Issues detected" -ForegroundColor Yellow }
}

exit 0
