name: PS Lint
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Run Analyzer (fail on warnings)
        shell: pwsh
        run: |
          $paths = @("C11/tools","C11/SHIELD4_ODESA","C03")
          Invoke-ScriptAnalyzer -Path C11 -Recurse -Severity Error -Settings .config/PSScriptAnalyzerSettings.psd1 | Tee-Object -Variable LintRes; if ($LintRes) { $LintRes | Format-Table -Auto; exit 1 }
 Tee-Object -Variable LintRes;
 if ($LintRes) { $LintRes | Format-Table -Auto; exit 1 }

