name: PS Tests
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

            - name: Cache PS modules
        uses: actions/cache@v4
        with:
          path: |
            ~\Documents\PowerShell\Modules
          key: ${{ runner.os }}-psmodules-${{ hashFiles('**/ps-tests.yml') }}
          restore-keys: |
            ${{ runner.os }}-psmodules-
      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Scope CurrentUser -Force

      - name: Run Pester
        shell: pwsh
        run: |
          Invoke-Pester -Path Tests -CI -Output Detailed

