name: PS Validate (Releases)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  validate-shield4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate SHIELD4_ODESA
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          Set-Location 
          ./C11/tools/Validate-Releases.ps1 -Module SHIELD4_ODESA -Root  -Strict
