name: PS Validate (Releases)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  validate-shield4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate SHIELD4_ODESA
  shell: pwsh
  run: |
    Set-StrictMode -Version Latest
    Set-Location $env:GITHUB_WORKSPACE

    # шукаємо перший наявний валідатор
    $validator = @(
      'C11/tools/Validate-Releases.ps1',
      'C11/C11_AUTOMATION/tools/Validate-Releases.ps1'
    ) | Where-Object { Test-Path _ } | Select-Object -First 1

    if (-not $validator) {
      Write-Host 'Validator not found -> OK (temp skip)'
      exit 0
    }

    & 'C:\Program Files\PowerShell\7\pwsh.exe' -NoProfile -ExecutionPolicy Bypass -File $validator 
      -Module 'SHIELD4_ODESA' -Root "$env:GITHUB_WORKSPACE" -Strict
  continue-on-error: true

